### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'List<Future<dynamic>>' in type cast

### ISSUE THREAD

**Issue by cvbni** [dart-lang/http_server#49]
**the client  side:test.html**
```
<!DOCTYPE html>
<html>
  <head>
    <title>test</title>
  </head>
  <body>
    <form method="post" action="http://127.0.0.1:8080" enctype="multipart/form-data">
      <input id="fileupload" name="myfile" type="file" placeholder="some file here..."/>
      <input type="submit" />
    </form>
  </body>
</html>
```
  
 
**the server side: main.dart**
 
...  
```
      try {
        server = await HttpServer.bind('0.0.0.0', 8080);
      } catch (e) {
        print("Couldn't bind to port 8080");
        exit(-1);
      }
      server.listen(uploadFile);
//upload a file---------------------------
  void uploadFile(HttpRequest request) {
    HttpBodyHandler.processRequest(request).then((body) {
     HttpBodyFileUpload fileUploaded = body.body['myfile'];
      print(fileUploaded.content);
    });
  }
```
  
  **then encounter the exception:**

```
E/flutter (18042): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (18042): type 'List<dynamic>' is not a subtype of type 'List<Future<dynamic>>' in type cast
E/flutter (18042): #0      Object._as (dart:core/runtime/libobject_patch.dart:67:25)
E/flutter (18042): #1      HttpBodyHandlerImpl.process.asFormData.<anonymous closure> (file:///D:/Users/istrator/Documents/FlutterProject/upload/lib/src/http_body_impl.dart:127:48)
E/flutter (18042): #2      _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter (18042): #3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (18042): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter (18042): #5      Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter (18042): #6      Future._complete (dart:async/future_impl.dart:467:7)
E/flutter (18042): #7      Stream.fold.<anonymous closure> (dart:async/stream.dart:716:18)
E/flutter (18042): #8      _RootZone.runGuarded (dart:async/zone.dart:1304:10)
E/flutter (18042): #9      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:383:13)
E/flutter (18042): #10     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:393:15)
E/flutter (18042): #11     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:277:7)
E/flutter (18042): #12     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
E/flutter (18042): #13     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
E/flutter (18042): #14     _RootZone.runGuarded (dart:async/zone.dart:1304:10)
E/flutter (18042): #15     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:383:13)
E/flutter (18042): #16     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:393:15)
E/flutter (18042): #17     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:277:7)
E/flutter (18042): #18     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
E/flutter (18042): #19     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
E/flutter (18042): #20     _RootZone.runGuarded (dart:async/zone.dart:1304:10)
E/flutter (18042): #21     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:383:13)
E/flutter (18042): #22     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:393:15)
E/flutter (18042): #23     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:277:7)
E/flutter (18042): #24     _SyncStreamController._sendDone (dart:async/stream_controller.dart:771:19)
E/flutter (18042): #25     _StreamController._closeUnchecked (dart:async/stream_controller.dart:628:7)
E/flutter (18042): #26     _StreamController.close (dart:async/stream_controller.dart:621:5)
E/flutter (18042): #27     new BoundMultipartStream.<anonymous closure>.<anonymous closure> (package:mime/src/bound_multipart_stream.dart:142:25)
E/flutter (18042): #28     _RootZone.runGuarded (dart:async/zone.dart:1304:10)
E/flutter (18042): #29     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:383:13)
E/flutter (18042): #30     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:393:15)
E/flutter (18042): #31     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:277:7)
E/flutter (18042): #32     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
E/flutter (18042): #33     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
E/flutter (18042): #34     _RootZone.runGuarded (dart:async/zone.dart:1304:10)
E/flutter (18042): #35     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:383:13)
E/flutter (18042): #36     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:393:15)
E/flutter (18042): #37     _DelayedDone.perform (dart:async/stream_impl.dart:597:14)
E/flutter (18042): #38     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694:11)
E/flutter (18042): #39     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654:7)
E/flutter (18042): #40     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (18042): #41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (18042): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (18042): type 'String' is not a subtype of type 'int' of 'index'
E/flutter (18042): #0      Uint8List.[] (dart:typed_data/runtime/libtyped_data_patch.dart)
E/flutter (18042): #1      _MyHomePageState.uploadFile.<anonymous closure> (file:///D:/Users/istrator/Documents/FlutterProject/upload/lib/main.dart:104:49)
E/flutter (18042): #2      _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter (18042): #3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (18042): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter (18042): #5      Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter (18042): #6      Future._complete (dart:async/future_impl.dart:467:7)
E/flutter (18042): #7      Stream.fold.<anonymous closure> (dart:async/stream.dart:716:18)
E/flutter (18042): #8      _RootZone.runGuarded (dart:async/zone.dart:1304:10)
E/flutter (18042): #9      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:383:13)
E/flutter (18042): #10     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:393:15)
E/flutter (18042): #11     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:277:7)
E/flutter (18042): #12     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
E/flutter (18042): #13     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
E/flutter (18042): #14     _RootZone.runGuarded (dart:async/zone.dart:1304:10)
E/flutter (18042): #15     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:383:13)
E/flutter (18042): #16     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:393:15)
E/flutter (18042): #17     _DelayedDone.perform (dart:async/stream_impl.dart:597:14)
E/flutter (18042): #18     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694:11)
E/flutter (18042): #19     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654:7)
E/flutter (18042): #20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (18042): #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by zoechi** [comment]
I guess this is the related SO question with some discussion https://stackoverflow.com/questions/50946376/flutterhow-to-upload-a-file-to-android-runing-flutter-httpserver (update question was deleted)

**Comment by cvbni** [comment]
Yes，[flutterhow-to-upload-a-file-to-android-runing-flutter-httpserver](https://stackoverflow.com/questions/50946376/flutterhow-to-upload-a-file-to-android-runing-flutter-httpserver), This question was posted my me,I tried to rewrite the http_server,but failed.I am a newbie in Flutter,too lots of thing to learn.

**Comment by rhymelph** [comment]
I also met, what should I do?

**Comment by zoechi** [comment]
@rhymelph Please provide the information that allows us to reproduce.
It's likely a problem with your code or an outdated dependency with code that is not yet fully updated to Dart 2.
With the provided information there is nothing we could do.

**Comment by rhymelph** [comment]
@zoechi Information is like @cvbni

**Comment by ngocdaothanh** [comment]
I'm having this problem too. I'm using Flutter 0.7.3-beta (the latest version listed at flutter.io as of today) on Mac.

http_server version is 0.9.8 (also latest version as of today):
https://pub.dartlang.org/packages/http_server

```
[VERBOSE-2:shell.cc(181)] Dart Error: Unhandled exception:
	type 'List<dynamic>' is not a subtype of type 'List<Future<dynamic>>' in type cast
	#0      Object._as (dart:core/runtime/libobject_patch.dart:74:25)
	#1      HttpBodyHandlerImpl.process.asFormData.<anonymous closure> (package:http_server/src/http_body_impl.dart:125:48)
	#2      _RootZone.runUnary (dart:async/zone.dart:1379:54)
	#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
	#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
	#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
	#6      Future._complete (dart:async/future_impl.dart:476:7)
	#7      Stream.fold.<anonymous closure> (dart:async/stream.dart:716:18)
	#8      _RootZone.runGuarded (dart:async/zone.dart:1302:10)
	#9      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
	#10     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
	#11     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
	#12     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
	#13     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
	#14     _RootZone.runGuarded (dart:async/zone.dart:1302:10)
	#15     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
	#16     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
	#17     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
	#18     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
	#19     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
	#20     _RootZone.runGuarded (dart:async/zone.dart:1302:10)
	#21     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
	#22     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
	#23     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
	#24     _SyncStreamController._sendDone (dart:async/stream_controller.dart:771:19)
	#25     _StreamController._closeUnchecked (dart:async/stream_controller.dart:628:7)
	#26     _StreamController.close (dart:async/stream_controller.dart:621:5)
	#27     new BoundMultipartStream.<anonymous closure>.<anonymous closure> (package:mime/src/bound_multipart_stream.dart:142:25)
	#28     _RootZone.runGuarded (dart:async/zone.dart:1302:10)
	#29     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
	#30     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
	#31     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
	#32     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
	#33     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
	#34     _RootZone.runGuarded (dart:async/zone.dart:1302:10)
	#35     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
	#36     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
	#37     _DelayedDone.perform (dart:async/stream_impl.dart:603:14)
	#38     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700:11)
	#39     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660:7)
	#40     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
	#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by ngocdaothanh** [comment]
@zoechi The problem is at `HttpBodyHandler.processRequest(request)`. Just pass in a file upload request, like in `test.html` reported above, and you can reproduce.

**Comment by ngocdaothanh** [comment]
When I debug in IntelliJ, `values` is of type `GrowableList<Future<List<dynamic>>>`, but for some reason the cast [`.then((values) => Future.wait(values as List<Future>))`](https://github.com/dart-lang/http_server/blob/3a9c378093733a06bfedaaad8227a5e416a960f2/lib/src/http_body_impl.dart#L125) failed (because of Dart 2 change?):

<img width="374" alt="screen shot 2018-09-12 at 7 57 10 am" src="https://user-images.githubusercontent.com/10095/45390304-12027000-b662-11e8-860d-6f7efbb8466c.png">

**Comment by ngocdaothanh** [comment]
I've created a PR to fix: https://github.com/dart-lang/http_server/pull/53

Can someone in the team review, merge, and release a new version please?
